// src/config/teams.js

// Unified password for all private leaderboards
export const UNIFIED_PASSWORD = process.env.PRIVATE_LEADERBOARD_PASSWORD || 'GDGC2025';

// Team configurations: teamId -> details
// Add/modify teams here. teamId is the URL segment after /private-leaderboard/
export const TEAMS = {
  'Sierra': {
    name: 'Sierra',
    participantEmails: [
    'revboss@gmail.com',
    'satwikrajv2@gmail.com',
    'sandhyanaseethalv@gmail.com',
    'tejashwini0302@gmail.com',
    'harshavardhanburra1@gmail.com',
    'g4neshhh674@gmail.com',
    'tannididurgakarthikeya@gmail.com',
    'swethachaganti15@gmail.com',
    'nathan.aryan14@gmail.com',
    'Sairam42090@gmail.com',
    'jellahansika258@gmail.com',
    'aditkgdgc@gmail.com',
    'arnavreddy196@gmail.com',
    'harshadityaadil19@gmail.com',
    'mahathik53@gmail.com',
    'sharonlillyy2@gmail.com',
    'sunayanagdgc@gmail.com',
    'reddy.official.31@gmail.com',
    'kotagiriasritha45@gmail.com',
    'kadalisowmya22@gmail.com',
    'vyshnaviyacha@gmail.com',
    'peratiakshitha40@gmail.com',
    'sharathknight831@gmail.com',
    'abdulamaan2903@gmail.com',
    'shishirreddy119@gmail.com',
    'hrishikeshcloud2@gmail.com'
    ],
    description: 'Private leaderboard for Sierra'
  },
  'Ballari': {
    name: 'Ballari',
    participantEmails: [
      'parnika2205@gmail.com',
      'nithingoli1402@gmail.com',
      'abinayabuddarapu@gmail.com',
      'rajavarapusathwik3@gmail.com',
      'parthivreddyb62@gmail.com',
      'lakinya20@gmail.com',
      'praneethgdgc@gmail.com',
      'Dshreya2004.16@gmail.com',
      'suhaaa2911@gmail.com',
      'gnanasaichinta@gmail.com',
      'nonithrao24@gmail.com',
      'nandakishorecloud@gmail.com',
      'likhin705@gmail.com',
      'vivekkrishna211@gmail.com',
      'gmgole7@gmail.com',
      'hansikam.2912@gmail.com',
      'shashank22004@gmail.com',
      'likithasrii14@gmail.com',
      'yadavharshitha214@gmail.com',
      'abhinaymusku10@gmail.com'
    ],
    description: 'Private leaderboard for Ballari'
  },
  'Aatagallu': {
    name: 'Aatagallu',
    participantEmails: [
      'kateghardeepak.gcsj@gmail.com',
'swagathyadav09@gmail.com',
'sirvinitesh81@gmail.com',
'harshireddi7@gmail.com',
'Swathik092005@gmail.com',
'ramarthi.bhavyasri7@gmail.com',
'nikithamailaram1@gmail.com',
'Vakkapathishivarao@gmail.com',
'jananigoud24@gamil.com',
'shalem0210@gmail.com',
'pothugantimadhulika9@gmail.com',
'aravindmaggidi5@gmail.com',
'gajawadavineela01@gmail.com',
'rangarajdeepu@gmail.com',
'suchisadula789@gmail.com',
'sahithimarri26@gmail.com',
'vadlaharshitha08@gmail.com',
'keerthanabrahma09@gmail.com',
'ramarthi.bhavyasri7@gmail.com',
'ramyaa.redddy@gmail.com',
'mosesgondi0@gmail.com'
    ],
    description: 'Private leaderboard for Aatagallu'
  },
  'Aspirers': {
    name: 'Aspirers',
    participantEmails: [
        'aiyogitha0@gmail.com',
        'yashashripenikalapati@gmail.com',
        'veersripriya@gmail.com',
        'nihaarsultana777@gmail.com',
        'anuja.anna4867@gmail.com',
        'pavanibodas11@gmail.com',
        'bhukyacharannaik16@gmail.com',
        'ananya040306@gmail.com',
        'umasuryasrinivasb@gmail.com',
        'rishwitareddy2005@gmail.com',
        'hardhikchowdary37@gmail.com',
        'gurralarajasiddarthareddy24@gmail.com',
        'venkatasaisriharshachiruvolu@gmail.com',
        'pranavmotesha1726@gmail.com',
        'sriman0067@gmail.com',
        'kattajathin0@gmail.com',
        'Sksamreeen27@gmail.com',
        'chandrakanth0603@gmail.com',   
        'vsanjana1217@gmail.com',
        'Orugantideeksha24@gmail.com',
        'kavyaa.gaddamm@gmail.com',
        'ramyaa.redddy@gmail.com',
        'mpranayreddy047@gmail.com',
        'bhavss658@gmail.com',
        'rishithaputta50@gmail.com' 
    ],
    description: 'Private leaderboard for Aspirers'
  },
  'Pookies': {
    name: 'Pookies',
    participantEmails: [
        'srujalmlrit@gmail.com', 
        'devarshini246@gmail.com', 
        'vaishnaviyadavvvv@gmail.com', 
        'moharanapratyusha15@gmail.com', 
        'samhithagoog2025@gmail.com', 
        'newmailkoushik@gmail.com', 
        'ashutoshsingh005a@gmail.com', 
        'pulisrilekha9116@gmail.com', 
        'ssamuelpramodd@gmail.com', 
        'malarouthusneha7@gmail.com', 
        'hiteshy9176@gmail.com', 
        'mahithnaidubandaru@gmail.com',
        'pekkan3ga77@gmail.com', 
        'eeshytva02@gmail.com', 
        'guptavidhi140108@gmail.com', 
        'rithvikgdgc@gmail.com', 
        'vfcopy2026@gmail.com', 
        'kaustubhaatripuraribhatla@gmail.com', 
        'praneethnarne08@gmail.com', 
        'jdadheech54@gmail.com', 
        'saiprakash15182005@gmail.com',
        'morizz.gdgc@gmail.com'
    ],
    description: 'Private leaderboard for Pookies'
  },
  'CJ':{
    name: 'CJ',
    participantEmails: [
      'akshayareddy2505@gmail.com',
'tanishqgoudcertigication@gmail.com',
'apoorva2kt@gmail.com',
'appasanikarthikeya2211@gmail.com',
'kalyanraghava51@gmail.com',
'giriprasadbanoth02@gmail.com',
'biyyanihari77@gmail.com',
'koushikchekuri732@gmail.com',
'nchetula@gmail.com',
'vijaygdgc@gmail.com',
'aniirudh2228@gmail.com',
'dugginalaajaykumar@gmail.com',
'ennawarrithvik0610@gmail.com',
'balu13g@gmail.com',
'harshireddi7@gmail.com',
'gcpwithankush03@gmail.com',
'sreesanthalt@gmail.com',
'kateghardeepak.gcsj@gmail.com',
'amithreddykongari@gmail.com',
'deepakvenkat196@gmail.com',
'rakeshnaidu231105@gmail.com',
'inomallesh@gmail.com',
'mruhan0017@gmail.com',
'nehabingi0@gmail.com',
'vedanshhsharmaa@gmail.com',
'tmahesh1407@gmail.com',
'swagathyadav09@gmail.com',
'vakkapathishivarao@gmail.com',
'shivamruthreddyyella9@gmail.com',
'yousuffbtw@gmail.com',
    ]
  },
  'Titans':{
    name:'Titans',
    participantEmails:[
      'hasadhikathottempudi9@gmail.com',
      'tmdineshkumar2628@gmail.com',
      'bodduakash8688@gmail.com',
      'anveshupre@gmail.com',
      'mdabdulrahaman5542@gmail.com',
      'amisha31patra@gmail.com',
      'gjan33366@gmail.com',
      'mrithvikchowdary99@gmail.com',
      'Meenakshidakara11@gmail.com',
      'nitisha9087@gmail.com',
      'vaishnavianugula2006@gmail.com',
      'nithishadaduvai@gmail.com',
      'adityaaaaaaarangdal@gmail.com',
      'kavyaa.gaddamm@gmail.com',
      'bhanupranitha2005@gmail.com',
      'akankshapravasthichincheti@gmail.com',
      'nithingoli1402@gmail.com'
    ]
  }
};

export const getTeam = (teamId) => TEAMS[teamId] || null;


